"""One-off / defensive check: verifies PEP_CLS.CLS_RTO_calling.delivery_partner has NOT become
a MySQL GENERATED column altered directly on the DB outside this codebase - the exact failure
mode this table's Postgres predecessor (lead_assignments) hit once (see git history: this
script used to run against Postgres, which rejected assign_leads.py's record_lead_assignments()
writing delivery_partner explicitly, since Postgres refuses any explicit value for a generated
column, and MySQL has the identical restriction).

Nothing in this repo's history ever defines delivery_partner as generated -
migrate_cls_rto_calling_schema.py adds it as a plain VARCHAR(64) NULL column. This is a no-op,
safe-to-run-anytime check; it only alters anything if the column has actually been turned
generated by something outside this codebase.

MySQL has no Postgres-style "ALTER COLUMN ... DROP EXPRESSION" that keeps a generated column's
already-materialized value while dropping only the expression. Restoring a plain column here
means redefining it via MODIFY COLUMN with its current type/nullability and no GENERATED
clause - since STORED generated columns are already written to disk, this only changes the
column's metadata, not its stored values.
"""
import sys
from pathlib import Path

import pymysql

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mysql_lib import get_credential

SCHEMA = "PEP_CLS"
TABLE = "CLS_RTO_calling"


def _column_info(cur):
    cur.execute(
        "SELECT is_nullable, column_type, generation_expression "
        "FROM information_schema.columns "
        "WHERE table_schema = %s AND table_name = %s AND column_name = 'delivery_partner'",
        (SCHEMA, TABLE),
    )
    return cur.fetchone()


def main():
    cred = get_credential()
    if cred is None:
        raise SystemExit("MYSQL_* credentials not configured.")
    conn = pymysql.connect(
        host=cred["host"], user=cred["user"], password=cred["password"],
        database=SCHEMA, port=cred["port"], ssl={"ssl": {}}, connect_timeout=15,
    )
    try:
        with conn.cursor() as cur:
            row = _column_info(cur)
            if row is None:
                print(f"delivery_partner column not found on {SCHEMA}.{TABLE} - nothing to do.")
                return
            is_nullable, column_type, generation_expression = row
            print(f"Current state: column_type={column_type!r}, generation_expression={generation_expression!r}")

            if not generation_expression:
                print("Column is already a plain column - nothing to do.")
                return

            null_clause = "NULL" if is_nullable == "YES" else "NOT NULL"
            cur.execute(f"ALTER TABLE `{TABLE}` MODIFY COLUMN `delivery_partner` {column_type} {null_clause}")
        conn.commit()
        print("Redefined the column without its generation expression - delivery_partner is now a plain column.")

        with conn.cursor() as cur:
            row = _column_info(cur)
            is_nullable, column_type, generation_expression = row
            print(f"Confirmed state: column_type={column_type!r}, generation_expression={generation_expression!r}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
